# Generated by Django 5.2.17 on 2026-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('instagram', 'Instagram'), ('referral', 'Referral')], max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], max_length=10, null=True)),
                ('latest_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCORED', 'Scored'), ('PENDING_SCORE', 'Pending Score'), ('DUPLICATE', 'Duplicate')], default='PENDING_SCORE', max_length=20)),
                ('repeat_lead', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
