# Generated by Django 5.2.17 on 2026-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=100, unique=True)),
                ('weight', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
