# Generated by Django 5.2.17 on 2026-09-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_scoringconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
                ('raw_ai_response', models.JSONField()),
                ('rule_breakdown', models.JSONField()),
                ('final_score', models.FloatField()),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'score_audit',
            },
        ),
    ]
